### ISSUE TITLE
Not fill indexes in docker env meilisearch 0.30.2

### ISSUE THREAD

**Issue by zofe** [laravel/scout#674]
- Scout Version: 9.4.10
- Scout Driver: MeiliSearch 
- meilisearch/meilisearch-php 0.24.2
- Laravel Version: 9.43.0
- Meilisearch CLI Version: 0.30.2
- PHP Version: 8.1.13

Scout import command create ony few index and doesn't import records (even though he says he did)

with this exact configuration in production scout works, scout commands (flush/import, etc..) works.
but in my local docker-compose environment it doesn't.

this is the relevant part of my docker-compose 
```

  meilisearch:
    image: getmeili/meilisearch:v0.30.2
    volumes:
      - ./data.ms:/data.ms
    environment:
      - MEILI_API_KEY=${MEILI_API_KEY}
      - MEILI_MASTER_KEY=${MEILI_MASTER_KEY}
      - MEILI_ENV=${MEILI_ENV}
      - MEILI_DB_PATH=/data.ms
```

may be a docker storage problem?
I'm on mac with docker on local env, and debian10 (no docker) on production
